@startuml
autonumber

actor "Collaborator" as CO
participant ":UploadFileUI" as UI
participant ":UploadFileController" as CTRL
participant "AplicacaoPOT" as _APP
participant "app\n:AplicacaoPOT" as APP
participant "session\n:UserSession" as SESSION
participant ":Platform" as PLAT
participant "orgR:\nOrganizationRecord" as ORGR
participant "org:\nOrganization" as ORG
participant "paytl:\nPaymentTransactionList" as PAYTL
participant "fil:FileReader" as FIL <<interface>>

activate CO
CO -> UI : begins to load a file (txt or csv)
activate UI

UI --> CO : requests the file that registers a set of transitions (filename)
deactivate UI

CO -> UI : enters the name of the file
activate UI

UI -> CTRL : getFileCsv(filename)
activate CTRL

CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSION: email = getUserEmail()
activate SESSION
deactivate SESSION

CTRL -> PLAT: orgR = getOrganizationRecord()
activate PLAT
deactivate PLAT

CTRL -> ORGR: org = getOrganizationByUserEmail(email)
activate ORGR
deactivate ORGR

CTRL -> ORG: par = getPaymentTransactionList()
activate ORG
deactivate ORG

CTRL -> PLAT : freerec = getFreelancerRecord()
activate PLAT
deactivate PLAT

CTRL -> ORG : taskList = getTaskList()
activate ORG
deactivate ORG


CTRL -> FIL: readNewFile(filename)
activate FIL
deactivate FIL
deactivate CTRL

UI -> CTRL: getTransactions()
activate CTRL
CTRL -> ORG: getPaymentTransactionList()
activate ORG
deactivate ORG
CTRL -> PAYTL: getPaymentTransactions()
activate PAYTL
deactivate PAYTL
deactivate CTRL

UI -> CO : displays the file, asking for confirmation
deactivate CTRL
deactivate UI

CO -> UI : confirms
activate UI


UI -> CO : success of the operation
deactivate ORG
deactivate CTRL
deactivate UI
deactivate CO

@enduml