@startuml
autonumber

actor "Time" as TEMPO

participant "task:NotifyFreelancersTask" as SCAT
participant "t: Timer" as TIMER
participant "regFreel\n:FreelancersRecord" as RFREEL


TEMPO -> PLAT : agendNotification()
activate TEMPO

activate PLAT
RFREEL -> SCAT** : create()
RFREEL -> RFREEL : date =getDateDefined()
RFREEL -> TIMER** : create()
RFREEL -> TIMER : schedule(task, date)
activate TIMER
deactivate RFREEL

TIMER -> SCAT : run()
activate SCAT
SCAT -> SCAT : sendEmail()

REF over SCAT
SD_sendEmail
end REF

SCAT -> SCAT : nextNotification()


SCAT -> RFREEL : regFreel = getRecordFreelancer()
activate RFREEL
deactivate RFREEL

SCAT -> RFREEL : scheduleAutomaticEmail()
activate RFREEL
deactivate RFREEL

deactivate TIMER
deactivate SCAT
deactivate TEMPO


@enduml