@startuml
autonumber
actor "Administrator" as ADM

activate ADM
ADM -> ":System" : begins to analyze the statistics describing the performance of all freelancers.

activate ":System"
":System" --> ADM : calculates and presents the statistics describing the performance of all freelancers.
deactivate ":System"

ADM -> ":System" : confirms
activate ":System"
":System" --> ADM : successful operation.
deactivate ":System"

deactivate ADM

@enduml