@startuml

skinparam classAttributeIconSize 0
hide attributes

interface PasswordGeneratorAlgorithm << interface >>
{
 +String generatePassword(String name, String email)
}


class ExternalAlgorithm1API
{
    +String generatePassword(String name, String email)
}

PasswordGeneratorAlgorithm <|.. ExternalAlgorithm1API

@enduml