@startuml
autonumber

actor "Manager or Collaborator" as CO
participant ":AnalyzeFreelancerStatisticsUI" as UI
participant ":AnalyzeFreelancerStatisticsController" as CTRL
participant "POTApplication" as _APP
participant "app\n:POTApplication" as APP
participant "session\n:UserSession" as SESSAO
participant ":Platform" as PLAT
participant "orgR:\nOrganizationsRecord" as ORGR
participant "org:\nOrganization" as ORG


activate CO
CO -> UI : starts to analyze the overall statistics about task execution times of one freelancer

activate UI
UI -> CTRL: getOrganization()

activate CTRL 

CTRL -> _APP: app = getInstance()
activate _APP
deactivate _APP

CTRL -> APP: session = getCurrentSession()
activate APP
deactivate APP

CTRL -> SESSAO: email = getUserEmail()
activate SESSAO
deactivate SESSAO

CTRL -> PLAT: orgR = getOrganizationsRecord()
activate PLAT
deactivate PLAT

CTRL -> ORGR: org = getOrganizationByUserEmail(email)
activate ORGR
deactivate ORGR
deactivate CTRL
 

UI -> CTRL : determinatePayOrg()
activate CTRL

CTRL -> ORG : determinatePayOrg(mapOrgPayment)
activate ORG
ref over ORG
SD_determinatePayOrg
end ref
CTRL <-- ORG : mapOrgPayment
deactivate ORG
deactivate CTRL


UI -> CTRL : calcMeanPayment()
activate CTRL
CTRL -> ORGR : calcMeanPayment(mapOrgPayment)
activate ORGR
deactivate ORGR
deactivate CTRL

UI -> CTRL : calcDeviationPayment()
activate CTRL
CTRL -> ORGR : calcDeviationPayment(mapOrgPayment,mapMeanPayments)
activate ORGR
deactivate ORGR
deactivate CTRL

UI -> CTRL : determinateDelayOrg()
activate CTRL
CTRL -> ORG : determinateDelayOrg(mapOrgDelay)
activate ORG
ref over ORG
SD_determinateDelayOrg
end ref
CTRL <-- ORG : mapOrgDelay
deactivate ORG
deactivate CTRL

UI -> CTRL : calcMeanDelay()
activate CTRL
CTRL -> ORGR : calcMeanDelay(mapOrgDelay)
activate ORGR
deactivate ORGR
deactivate CTRL

UI -> CTRL : calcDeviationDelay()
activate CTRL
CTRL -> ORGR : calcDeviationDelay(mapOrgDelay,mapMeanDelays)
activate ORGR
deactivate ORGR
deactivate CTRL



UI --> CO : presents the statistics about task execution times\nand payments of each and all the freelancers working for that organization.
deactivate UI


deactivate CO
@enduml
