@startuml

usecase UC1 as "UC1 - Create Freelancer"
usecase UC2 as "UC2 - Create Tasks"
usecase UC3 as "UC3 - Create Payment"
usecase UC4 as "UC4 - Upload File"
usecase UC5 as "UC5 - Set Day of Payment"


actor "Collaborator" as CO
actor "Manager of Organization" as MO

left to right direction
CO --> (UC1)
CO --> (UC2)
CO --> (UC3)
MO --> (UC4)

MO -->(UC5)

@enduml