@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Platform {
  -String designation
}

class Organization {
  -String name
}

class Collaborator {
  -String name
  -String email
}


class User {
  -String email
  -String password
}

class Freelancer {
  -String id
  -String name
  -String expertiseLevel
  -String email
  -String NIF
  -String IBAN
  -String address
  -String country
  }

class Task {
 -String id
 -String briefDescription
 -Integer timeDuration
 -Double costPerHour
 -String taskCategory
}

class TaskExecution {
 -Date endDate
 -Double delay
 -String workQualityDescription
}

class PaymentTransaction{
}

class ManagerOfOrganization {
  -String name
  -String email
}

class PaymentDay {
  -Date timeOfDay
  -Date dayOfMonth
}

Organization "1" -- "1" ManagerOfOrganization : has >
ManagerOfOrganization "1" -- "1" PaymentDay : sets >
Platform "1" -- "*" Organization : has registered >
Platform "1" -- "*" Freelancer : has/uses >
Organization "1" -- "1" Collaborator: has >
Organization "1" -- "*" Task: has >
Organization "1" -- "*" PaymentTransaction: has >
Collaborator "0..1" -- "1" User: acts like >
Freelancer "0..1" -- "1" User: acts like >
Collaborator "1" -- "*" Freelancer: create >
Collaborator "1" -- "*" Task: create >
Collaborator "1" -- "*" PaymentTransaction: create >
PaymentTransaction "1" -- "1" Freelancer: related to >
PaymentTransaction "1" -- "1" Task: relates to >
PaymentTransaction "1" -- "1" TaskExecution: related to >
Task "1" -- "1" TaskExecution: has >
PaymentDay "1" -- "0..*" PaymentTransaction : is related to

@enduml
